# Generated by Django 6.0.1 on 2026-01-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpelerID', models.IntegerField(default=0)),
                ('punten', models.IntegerField(default=0)),
                ('matchCode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Speler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=25)),
                ('voorNaam', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
